repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: name-tests-test
        args:
          - "--django"
      - id: requirements-txt-fixer
      - id: check-symlinks
      - id: check-docstring-first
      - id: detect-aws-credentials
        args:
          - "--allow-missing-credentials"
      - id: detect-private-key
      - id: forbid-new-submodules
      - id: check-added-large-files
      - id: check-builtin-literals
        args:
          - "--ignore=dict,list"
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: debug-statements

  # checking code’s compliance - PEP8
  - repo: "https://github.com/PyCQA/flake8"
    rev: 5.0.4
    hooks:
      - id: flake8
        args:
          - "--max-line-length=120"
          - "--max-complexity=30"
          - '--select=E'
        additional_dependencies:
          - pep8-naming
          - flake8-typing-imports==1.10.1
          - flake8-bugbear
          - flake8-mutable
          - flake8-print
          - flake8-simplify

  # uncompromising Python code formatter - The Black Code Style
  - repo: "https://github.com/psf/black"
    rev: 22.10.0
    hooks:
      - id: black

  # upgrading syntax of new python version
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    - id: pyupgrade

  # removing unused import statements
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.1.1
    hooks:
      - id: pycln
        args: [--all]

  # sorting import statements
  - repo: "https://github.com/pycqa/isort"
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)

  # rewriting documentation files in place
  - repo: "https://github.com/asottile/blacken-docs"
    rev: v1.12.1
    hooks:
      - id: blacken-docs
        additional_dependencies:
          - black==v21.5b1
        entry: blacken-docs --skip-errors

  # checking migrations
  - repo: local
    hooks:
      - id: django-migrations
        name: Check django migrations
        entry: python backend/manage.py makemigrations --noinput --dry-run
        language: system
        types: [python]
        pass_filenames: false
        require_serial: true
